### ISSUE TITLE
Banned from island, but bypassed with warp

### ISSUE THREAD

**Issue by Albert481** [BentoBoxWorld/Warps#94] opened 2021-01-07 13:10 UTC
#### Describe the bug
There is a command called the /is ban (name) that bans a player to go your island. However, it can be bypassed by the /is warp (name) sign. 

#### Steps to reproduce the behavior
We asked a player that I personally banned from our island to our island. Afterwards, Another player tested to let the banned player use the /is warp (name). The player successfully entered the island.

#### Expected behavior
Player should be blocked.

##### Output of `/bbox version` (Mandatory)

```
[21:09:59 INFO]: Running Invalid (TUINITY) 1.16.3.
[21:09:59 INFO]: BentoBox version: 1.15.3
[21:09:59 INFO]: Database: JSON
[21:09:59 INFO]: Loaded Game Worlds:
[21:09:59 INFO]: bskyblock_world (BSkyBlock): Overworld, Nether, The End
[21:09:59 INFO]: Loaded Addons:
[21:09:59 INFO]: Biomes 1.13.0 (ENABLED)
[21:09:59 INFO]: Border 2.0.0 (ENABLED)
[21:09:59 INFO]: BSkyBlock 1.14.3 (ENABLED)
[21:09:59 INFO]: Challenges 0.8.3 (ENABLED)
[21:09:59 INFO]: Chat 1.1.1 (ENABLED)
[21:09:59 INFO]: ControlPanel 1.7.0 (ENABLED)
[21:09:59 INFO]: ExtraMobs 1.11.0.3 (ENABLED)
[21:09:59 INFO]: Level 2.5.0 (ENABLED)
[21:09:59 INFO]: Likes 2.0.0 (ENABLED)
[21:09:59 INFO]: Limits 1.15.0 (ENABLED)
[21:09:59 INFO]: MagicCobblestoneGenerator 2.1.0 (ENABLED)
[21:09:59 INFO]: Upgrades 0.2.0-SNAPSHOT-b79 (ENABLED)
[21:09:59 INFO]: Warps 1.9.7 (ENABLED)
```

**Comment by tastybento** [comment] 2021-01-09 05:18
Hmm. I cannot replicate this. If I try to warp to an island that I've been banned from whether I use Warps or not, BentoBox gives me this error:
<img width="396" alt="Screen Shot 2021-01-08 at 9 10 22 PM" src="https://user-images.githubusercontent.com/4407265/104083824-becf6680-51f6-11eb-80d5-19d417a15c04.png">

This can be bypassed by Ops or players with the `bskyblock.mod.bypassban` permission. Could the player have that perm or the `BSkyBlock.mod.*` perm?

**Comment by Kesims** [comment] 2021-01-09 10:53
I cant replicate that too, but when banned player uses the warp, it can spam island owner with "Player used your warp" message. (The banned player actually cant warp to the island, but can spam island owner)

**Comment by tastybento** [comment] 2021-01-09 23:35
Okay, this is a dupe of #69

**Closed by tastybento** 2021-01-09 23:35 UTC
Labels: cannot replicate, investigating
